//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminKullanicilari
    {
        public long LOGICALREF { get; set; }
        public string MailAdresi { get; set; }
        public string Sifre { get; set; }
        public string AdiSoyadi { get; set; }
        public string GSM { get; set; }
        public Nullable<bool> Statu { get; set; }
        public Nullable<System.DateTime> SifreDegistirmeTarihi { get; set; }
        public string GeciciSifre { get; set; }
    }
}
