//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANKT_Sorular
    {
        public int LOGICALREF { get; set; }
        public Nullable<int> MasterRef { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string Metin { get; set; }
        public string CevapTipi { get; set; }
    }
}
