//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANKT_Sonuclar
    {
        public int LOGICALREF { get; set; }
        public Nullable<int> SoruRef { get; set; }
        public string Cevap { get; set; }
        public string BayiKullaniciMail { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public string BayiKodu { get; set; }
        public string BayiAdi { get; set; }
        public Nullable<int> MasterRef { get; set; }
    }
}
