//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BayiKullaniciYetkileri
    {
        public int LOGICALREF { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<bool> FiyatListesiGorme { get; set; }
        public Nullable<bool> SiparisOlusturma { get; set; }
        public Nullable<bool> SiparisleriGorme { get; set; }
        public Nullable<bool> IrsaliyeleriGorme { get; set; }
        public Nullable<bool> HesapEkstresiGorme { get; set; }
        public Nullable<bool> RaporlariGorme { get; set; }
        public Nullable<bool> AnketleriGorme { get; set; }
        public Nullable<bool> SikayetleriGorme { get; set; }
        public Nullable<bool> BelgeleriGorme { get; set; }
        public Nullable<bool> FirmaAdminiMi { get; set; }
    }
}
