//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BayiEvraklari
    {
        public int LOGICALREF { get; set; }
        public string BayiKodu { get; set; }
        public string BayiAdi { get; set; }
        public string BayilikSozlesmesi { get; set; }
        public string BayiPortalSozlesmesi { get; set; }
        public string CariHesapSozlesmesi { get; set; }
        public string VergiLevhasi { get; set; }
        public string ImzaSirkusu { get; set; }
        public string TicaretSicilGazetesi { get; set; }
        public string NufusCuzdaniFotokopisi { get; set; }
        public string Diger { get; set; }
    }
}
