//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitliAdresler
    {
        public long LOGICALREF { get; set; }
        public string BayiKodu { get; set; }
        public string AdresBasligi { get; set; }
        public string IlgiliKisi { get; set; }
        public string IlgiliKisiTel { get; set; }
        public Nullable<bool> FabrikaTeslimMi { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string DetayliAdres { get; set; }
    }
}
