//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long LOGICALREF { get; set; }
        public Nullable<bool> AdminMi { get; set; }
        public string MailAdresi { get; set; }
        public string GezindigiSayfa { get; set; }
        public string IpAdresi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string BayiAdi { get; set; }
    }
}
