//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSetting
    {
        public int LOGICALREF { get; set; }
        public string MailAdresi { get; set; }
        public string MailAdi { get; set; }
        public string MesajSifresi { get; set; }
        public string SmtpServer { get; set; }
        public Nullable<int> SmtpPort { get; set; }
        public Nullable<bool> Status { get; set; }
        public string HataMesajiGidecekGsm { get; set; }
    }
}
