//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IZOKALEPORTALEntities : DbContext
    {
        public IZOKALEPORTALEntities()
            : base("name=IZOKALEPORTALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminKullanicilari> AdminKullanicilari { get; set; }
        public virtual DbSet<BayiKullanicilari> BayiKullanicilari { get; set; }
        public virtual DbSet<KayitliAdresler> KayitliAdresler { get; set; }
        public virtual DbSet<SiparisBasliklari> SiparisBasliklari { get; set; }
        public virtual DbSet<SiparisIcerikleri> SiparisIcerikleri { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<BayiKullaniciYetkileri> BayiKullaniciYetkileri { get; set; }
        public virtual DbSet<AdminKullaniciYetkisi> AdminKullaniciYetkisi { get; set; }
        public virtual DbSet<Duyurular> Duyurular { get; set; }
        public virtual DbSet<TeklifIcerikleri> TeklifIcerikleri { get; set; }
        public virtual DbSet<BayiEvraklari> BayiEvraklari { get; set; }
        public virtual DbSet<Sikayet> Sikayet { get; set; }
        public virtual DbSet<SiparisVeTeklifFormuGonderilecekMailler> SiparisVeTeklifFormuGonderilecekMailler { get; set; }
        public virtual DbSet<SikayetBildirimiAtilacakKisiler> SikayetBildirimiAtilacakKisiler { get; set; }
        public virtual DbSet<ANKT_Master> ANKT_Master { get; set; }
        public virtual DbSet<ANKT_SabitCevaplar> ANKT_SabitCevaplar { get; set; }
        public virtual DbSet<ANKT_Sonuclar> ANKT_Sonuclar { get; set; }
        public virtual DbSet<ANKT_Sorular> ANKT_Sorular { get; set; }
        public virtual DbSet<YuklemeTalebiDetayi> YuklemeTalebiDetayi { get; set; }
        public virtual DbSet<MailSetting> MailSetting { get; set; }
        public virtual DbSet<YuklemeTalebiMaster> YuklemeTalebiMaster { get; set; }
        public virtual DbSet<TeklifBasliklari> TeklifBasliklari { get; set; }
    
        public virtual ObjectResult<BayilerinPortalKullanimSayisi_Result> BayilerinPortalKullanimSayisi(string tarih)
        {
            var tarihParameter = tarih != null ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BayilerinPortalKullanimSayisi_Result>("BayilerinPortalKullanimSayisi", tarihParameter);
        }
    }
}
