//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sikayet
    {
        public long LOGICALREF { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public string FormNo { get; set; }
        public Nullable<System.DateTime> FormTarih { get; set; }
        public string BayiKodu { get; set; }
        public string BayiAdi { get; set; }
        public string SantiyeAdi { get; set; }
        public string IrtibatKurulacakKisi { get; set; }
        public string IrtibatNo { get; set; }
        public string UrunGrubu { get; set; }
        public string BildirimSebebi { get; set; }
        public string UrunAciklama { get; set; }
        public string DetayliAciklama { get; set; }
        public string PartiNo { get; set; }
        public Nullable<System.DateTime> UretimTarihi { get; set; }
        public string UrunMiktari { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public string SikayetOlusturan { get; set; }
        public string Durum { get; set; }
        public string DegistirmeTarihi { get; set; }
        public string FirmaCevabi { get; set; }
        public string OnIncelemeSekli { get; set; }
        public string OnIncelemeSorumlusu { get; set; }
        public string OnIncelemeSonucu { get; set; }
        public string OnIncelemeYapilanIslemSorumlusu { get; set; }
        public string OnIncelemeYapilanIsler { get; set; }
        public string OnIncelemeIslemYapan { get; set; }
        public Nullable<System.DateTime> OnIncelemeIslemTarihi { get; set; }
        public string SikayetMaliyeti { get; set; }
        public string SorumluDepartman { get; set; }
        public string KokNedenAnalizi { get; set; }
        public string LoginOlunanMail { get; set; }
    }
}
