//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeklifBasliklari
    {
        public long LOGICALREF { get; set; }
        public string BayiKodu { get; set; }
        public string BayiAdi { get; set; }
        public string MailAdresi { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<System.DateTime> TeklifSonGecerlilikTarihi { get; set; }
        public string FiyatListesi { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public Nullable<bool> FabrikaTeslimMi { get; set; }
        public Nullable<bool> OnaylandiMi { get; set; }
        public Nullable<System.DateTime> OnaylanmaTarihi { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
        public string SilinmeSebebi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public Nullable<int> BaglantiLref { get; set; }
        public string BaglantiAciklamasi { get; set; }
        public Nullable<bool> SipariseDonduMu { get; set; }
    }
}
