//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YuklemeTalebiMaster
    {
        public long LOGICALREF { get; set; }
        public Nullable<System.DateTime> BayiTalebiYuklemeTarihi { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public string SiparisNo { get; set; }
        public string Plakalar { get; set; }
        public string TalepAciklamasi { get; set; }
        public string BayiKodu { get; set; }
        public string BayiAdi { get; set; }
        public Nullable<System.DateTime> TalepAcilisTarihi { get; set; }
        public Nullable<System.DateTime> FirmaYuklemeTarihi { get; set; }
        public string FirmaAciklamasi { get; set; }
        public string TalebiAcan { get; set; }
        public Nullable<bool> YuklendiMi { get; set; }
    }
}
