//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YuklemeTalebiDetayi
    {
        public long LOGICALREF { get; set; }
        public Nullable<long> YuklemeTeklifiMasterLogicalref { get; set; }
        public string MalzemeKodu { get; set; }
        public string MalzemeAciklamasi { get; set; }
        public string Birim { get; set; }
        public Nullable<double> BekleyenMiktar { get; set; }
        public Nullable<double> YuklemeTalepMiktari { get; set; }
    }
}
