//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaleBlokBims.M2BWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="M2BWebService.IZOKALEAPISoap")]
    public interface IZOKALEAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletFiyatiniAl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PaletFiyatiniAl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletFiyatiniAl", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PaletFiyatiniAlAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bayiler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KaleBlokBims.M2BWebService.Musteriler[] Bayiler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bayiler", ReplyAction="*")]
        System.Threading.Tasks.Task<KaleBlokBims.M2BWebService.Musteriler[]> BayilerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IlveIlceleriGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IlveIlceleriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IlveIlceleriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IlveIlceleriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SistemKalemleriBilgileriAl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KaleBlokBims.M2BWebService.SistemKalemleriBilgileri[] SistemKalemleriBilgileriAl(string anaGrup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SistemKalemleriBilgileriAl", ReplyAction="*")]
        System.Threading.Tasks.Task<KaleBlokBims.M2BWebService.SistemKalemleriBilgileri[]> SistemKalemleriBilgileriAlAsync(string anaGrup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MalzemeListesi(string BayiKodu, string FiyatListesiKodu, string baglantiLREF, string SPECODE1, string SPECODE2, string Il, string Ilce, bool fabrikaTeslimMi, double GuncelUSD, double GuncelEUR, string PAYPLANREF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeListesi", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MalzemeListesiAsync(string BayiKodu, string FiyatListesiKodu, string baglantiLREF, string SPECODE1, string SPECODE2, string Il, string Ilce, bool fabrikaTeslimMi, double GuncelUSD, double GuncelEUR, string PAYPLANREF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YonetimRaporlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string YonetimRaporlari(string tabloAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YonetimRaporlari", ReplyAction="*")]
        System.Threading.Tasks.Task<string> YonetimRaporlariAsync(string tabloAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecilebilirFiyatListeleri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KaleBlokBims.M2BWebService.FiyatListesiBakiye[] SecilebilirFiyatListeleri(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecilebilirFiyatListeleri", ReplyAction="*")]
        System.Threading.Tasks.Task<KaleBlokBims.M2BWebService.FiyatListesiBakiye[]> SecilebilirFiyatListeleriAsync(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnaGruplar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AnaGruplar(string FiyatListesi, string baglantiLREF, string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AnaGruplar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AnaGruplarAsync(string FiyatListesi, string baglantiLREF, string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HesapEkstresi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HesapEkstresi(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HesapEkstresi", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HesapEkstresiAsync(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IrsaliyeFisiSatirlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IrsaliyeFisiSatirlari(int stFicheRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IrsaliyeFisiSatirlari", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IrsaliyeFisiSatirlariAsync(int stFicheRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriyeSevkRaporu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MusteriyeSevkRaporu(string BayiKodu, string BaslangicTarih, string BitisTarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriyeSevkRaporu", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MusteriyeSevkRaporuAsync(string BayiKodu, string BaslangicTarih, string BitisTarihi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IrsaliyeFisleri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IrsaliyeFisleri(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IrsaliyeFisleri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IrsaliyeFisleriAsync(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiparisFisiSatirIrsaliyeleri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SiparisFisiSatirIrsaliyeleri(int orfLineRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiparisFisiSatirIrsaliyeleri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SiparisFisiSatirIrsaliyeleriAsync(int orfLineRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiparisFisiSatirlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SiparisFisiSatirlari(int OrFicheRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiparisFisiSatirlari", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SiparisFisiSatirlariAsync(int OrFicheRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiparisFisleri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SiparisFisleri(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SiparisFisleri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SiparisFisleriAsync(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TumBayilerinBaglantiBakiyeOzeti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TumBayilerinBaglantiBakiyeOzeti();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TumBayilerinBaglantiBakiyeOzeti", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TumBayilerinBaglantiBakiyeOzetiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SozlesmeyeBagliCarilerVeSatisElemanlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        KaleBlokBims.M2BWebService.SozlesmeVeCarileri[] SozlesmeyeBagliCarilerVeSatisElemanlari();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SozlesmeyeBagliCarilerVeSatisElemanlari", ReplyAction="*")]
        System.Threading.Tasks.Task<KaleBlokBims.M2BWebService.SozlesmeVeCarileri[]> SozlesmeyeBagliCarilerVeSatisElemanlariAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BaglantiBakiyeOzeti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BaglantiBakiyeOzeti(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BaglantiBakiyeOzeti", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BaglantiBakiyeOzetiAsync(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HesapOzeti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HesapOzeti(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HesapOzeti", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HesapOzetiAsync(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriyeBagliCariBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MusteriyeBagliCariBilgileri(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriyeBagliCariBilgileri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MusteriyeBagliCariBilgileriAsync(string BayiKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCFOdemePlanlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WCFOdemePlanlari();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCFOdemePlanlari", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WCFOdemePlanlariAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCFSatisElemanlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WCFSatisElemanlari();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCFSatisElemanlari", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WCFSatisElemanlariAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsyeriBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsyeriBilgileri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsyeriBilgileri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IsyeriBilgileriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FabrikaBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FabrikaBilgileri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FabrikaBilgileri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> FabrikaBilgileriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BolumBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BolumBilgileri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BolumBilgileri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BolumBilgileriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbarBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AmbarBilgileri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbarBilgileri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AmbarBilgileriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCFSozlesmeBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WCFSozlesmeBilgileri(string BayiKodu, int BaglantiLREF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WCFSozlesmeBilgileri", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WCFSozlesmeBilgileriAsync(string BayiKodu, int BaglantiLREF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        System.Threading.Tasks.Task<string> testAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/M2BSiparisOlustur", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string M2BSiparisOlustur(string Ambar, KaleBlokBims.M2BWebService.M2BWCFBaslik Baslik, KaleBlokBims.M2BWebService.M2BWCFTransaction[] Transactions, KaleBlokBims.M2BWebService.CariSevkAdresi AdresBilgileri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/M2BSiparisOlustur", ReplyAction="*")]
        System.Threading.Tasks.Task<string> M2BSiparisOlusturAsync(string Ambar, KaleBlokBims.M2BWebService.M2BWCFBaslik Baslik, KaleBlokBims.M2BWebService.M2BWCFTransaction[] Transactions, KaleBlokBims.M2BWebService.CariSevkAdresi AdresBilgileri);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Musteriler : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lOGICALREFField;
        
        private string bayiAdiField;
        
        private string bayiKoduField;
        
        private string aDDR1Field;
        
        private string aDDR2Field;
        
        private string cITYField;
        
        private string tOWNField;
        
        private string wEBURLField;
        
        private string tELNR1Field;
        
        private string tELNR2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LOGICALREF {
            get {
                return this.lOGICALREFField;
            }
            set {
                this.lOGICALREFField = value;
                this.RaisePropertyChanged("LOGICALREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BayiAdi {
            get {
                return this.bayiAdiField;
            }
            set {
                this.bayiAdiField = value;
                this.RaisePropertyChanged("BayiAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BayiKodu {
            get {
                return this.bayiKoduField;
            }
            set {
                this.bayiKoduField = value;
                this.RaisePropertyChanged("BayiKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ADDR1 {
            get {
                return this.aDDR1Field;
            }
            set {
                this.aDDR1Field = value;
                this.RaisePropertyChanged("ADDR1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ADDR2 {
            get {
                return this.aDDR2Field;
            }
            set {
                this.aDDR2Field = value;
                this.RaisePropertyChanged("ADDR2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TOWN {
            get {
                return this.tOWNField;
            }
            set {
                this.tOWNField = value;
                this.RaisePropertyChanged("TOWN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string WEBURL {
            get {
                return this.wEBURLField;
            }
            set {
                this.wEBURLField = value;
                this.RaisePropertyChanged("WEBURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TELNR1 {
            get {
                return this.tELNR1Field;
            }
            set {
                this.tELNR1Field = value;
                this.RaisePropertyChanged("TELNR1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TELNR2 {
            get {
                return this.tELNR2Field;
            }
            set {
                this.tELNR2Field = value;
                this.RaisePropertyChanged("TELNR2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CariSevkAdresi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adresBasligiField;
        
        private string aciklama1Field;
        
        private string adres1Field;
        
        private string adres2Field;
        
        private string ilField;
        
        private string ilceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AdresBasligi {
            get {
                return this.adresBasligiField;
            }
            set {
                this.adresBasligiField = value;
                this.RaisePropertyChanged("AdresBasligi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aciklama1 {
            get {
                return this.aciklama1Field;
            }
            set {
                this.aciklama1Field = value;
                this.RaisePropertyChanged("Aciklama1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Adres1 {
            get {
                return this.adres1Field;
            }
            set {
                this.adres1Field = value;
                this.RaisePropertyChanged("Adres1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Adres2 {
            get {
                return this.adres2Field;
            }
            set {
                this.adres2Field = value;
                this.RaisePropertyChanged("Adres2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Il {
            get {
                return this.ilField;
            }
            set {
                this.ilField = value;
                this.RaisePropertyChanged("Il");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Ilce {
            get {
                return this.ilceField;
            }
            set {
                this.ilceField = value;
                this.RaisePropertyChanged("Ilce");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class M2BWCFTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int satirTipiField;
        
        private string malzemeKoduField;
        
        private string hareketOzelKoduField;
        
        private double miktarField;
        
        private double birimFiyatField;
        
        private double toplamField;
        
        private double iskontoOraniField;
        
        private double kdvField;
        
        private int kdvHaricmi0Field;
        
        private string satirAciklamasiField;
        
        private string birimField;
        
        private double indirimOraniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SatirTipi {
            get {
                return this.satirTipiField;
            }
            set {
                this.satirTipiField = value;
                this.RaisePropertyChanged("SatirTipi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MalzemeKodu {
            get {
                return this.malzemeKoduField;
            }
            set {
                this.malzemeKoduField = value;
                this.RaisePropertyChanged("MalzemeKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HareketOzelKodu {
            get {
                return this.hareketOzelKoduField;
            }
            set {
                this.hareketOzelKoduField = value;
                this.RaisePropertyChanged("HareketOzelKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Miktar {
            get {
                return this.miktarField;
            }
            set {
                this.miktarField = value;
                this.RaisePropertyChanged("Miktar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double BirimFiyat {
            get {
                return this.birimFiyatField;
            }
            set {
                this.birimFiyatField = value;
                this.RaisePropertyChanged("BirimFiyat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double Toplam {
            get {
                return this.toplamField;
            }
            set {
                this.toplamField = value;
                this.RaisePropertyChanged("Toplam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double IskontoOrani {
            get {
                return this.iskontoOraniField;
            }
            set {
                this.iskontoOraniField = value;
                this.RaisePropertyChanged("IskontoOrani");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Kdv {
            get {
                return this.kdvField;
            }
            set {
                this.kdvField = value;
                this.RaisePropertyChanged("Kdv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int KdvHaricmi0 {
            get {
                return this.kdvHaricmi0Field;
            }
            set {
                this.kdvHaricmi0Field = value;
                this.RaisePropertyChanged("KdvHaricmi0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SatirAciklamasi {
            get {
                return this.satirAciklamasiField;
            }
            set {
                this.satirAciklamasiField = value;
                this.RaisePropertyChanged("SatirAciklamasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Birim {
            get {
                return this.birimField;
            }
            set {
                this.birimField = value;
                this.RaisePropertyChanged("Birim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double IndirimOrani {
            get {
                return this.indirimOraniField;
            }
            set {
                this.indirimOraniField = value;
                this.RaisePropertyChanged("IndirimOrani");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class M2BWCFBaslik : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tarihField;
        
        private string cariLREFField;
        
        private string belgeNoField;
        
        private string ozelKodField;
        
        private string yetkiKoduField;
        
        private string adresBasligiField;
        
        private string aciklama1Field;
        
        private string aciklama2Field;
        
        private string aciklama3Field;
        
        private string aciklama4Field;
        
        private string odemeTipiKoduField;
        
        private string ticariIslemGrubuField;
        
        private string satisElemaniKoduField;
        
        private string teslimSekliKoduField;
        
        private string projeKoduField;
        
        private string musteriSiparisNoField;
        
        private string dokumanIzlemeNumarasiField;
        
        private int sozlesmeReferansiField;
        
        private string isyeriField;
        
        private string bolumField;
        
        private string fabrikaField;
        
        private string ambarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
                this.RaisePropertyChanged("Tarih");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CariLREF {
            get {
                return this.cariLREFField;
            }
            set {
                this.cariLREFField = value;
                this.RaisePropertyChanged("CariLREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BelgeNo {
            get {
                return this.belgeNoField;
            }
            set {
                this.belgeNoField = value;
                this.RaisePropertyChanged("BelgeNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OzelKod {
            get {
                return this.ozelKodField;
            }
            set {
                this.ozelKodField = value;
                this.RaisePropertyChanged("OzelKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string YetkiKodu {
            get {
                return this.yetkiKoduField;
            }
            set {
                this.yetkiKoduField = value;
                this.RaisePropertyChanged("YetkiKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AdresBasligi {
            get {
                return this.adresBasligiField;
            }
            set {
                this.adresBasligiField = value;
                this.RaisePropertyChanged("AdresBasligi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Aciklama1 {
            get {
                return this.aciklama1Field;
            }
            set {
                this.aciklama1Field = value;
                this.RaisePropertyChanged("Aciklama1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Aciklama2 {
            get {
                return this.aciklama2Field;
            }
            set {
                this.aciklama2Field = value;
                this.RaisePropertyChanged("Aciklama2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Aciklama3 {
            get {
                return this.aciklama3Field;
            }
            set {
                this.aciklama3Field = value;
                this.RaisePropertyChanged("Aciklama3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Aciklama4 {
            get {
                return this.aciklama4Field;
            }
            set {
                this.aciklama4Field = value;
                this.RaisePropertyChanged("Aciklama4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OdemeTipiKodu {
            get {
                return this.odemeTipiKoduField;
            }
            set {
                this.odemeTipiKoduField = value;
                this.RaisePropertyChanged("OdemeTipiKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TicariIslemGrubu {
            get {
                return this.ticariIslemGrubuField;
            }
            set {
                this.ticariIslemGrubuField = value;
                this.RaisePropertyChanged("TicariIslemGrubu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SatisElemaniKodu {
            get {
                return this.satisElemaniKoduField;
            }
            set {
                this.satisElemaniKoduField = value;
                this.RaisePropertyChanged("SatisElemaniKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TeslimSekliKodu {
            get {
                return this.teslimSekliKoduField;
            }
            set {
                this.teslimSekliKoduField = value;
                this.RaisePropertyChanged("TeslimSekliKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ProjeKodu {
            get {
                return this.projeKoduField;
            }
            set {
                this.projeKoduField = value;
                this.RaisePropertyChanged("ProjeKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string MusteriSiparisNo {
            get {
                return this.musteriSiparisNoField;
            }
            set {
                this.musteriSiparisNoField = value;
                this.RaisePropertyChanged("MusteriSiparisNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DokumanIzlemeNumarasi {
            get {
                return this.dokumanIzlemeNumarasiField;
            }
            set {
                this.dokumanIzlemeNumarasiField = value;
                this.RaisePropertyChanged("DokumanIzlemeNumarasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int SozlesmeReferansi {
            get {
                return this.sozlesmeReferansiField;
            }
            set {
                this.sozlesmeReferansiField = value;
                this.RaisePropertyChanged("SozlesmeReferansi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Isyeri {
            get {
                return this.isyeriField;
            }
            set {
                this.isyeriField = value;
                this.RaisePropertyChanged("Isyeri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Bolum {
            get {
                return this.bolumField;
            }
            set {
                this.bolumField = value;
                this.RaisePropertyChanged("Bolum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Fabrika {
            get {
                return this.fabrikaField;
            }
            set {
                this.fabrikaField = value;
                this.RaisePropertyChanged("Fabrika");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Ambar {
            get {
                return this.ambarField;
            }
            set {
                this.ambarField = value;
                this.RaisePropertyChanged("Ambar");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SozlesmeVeCarileri : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int baglantiLREFField;
        
        private int cariLREFField;
        
        private string cariKoduField;
        
        private string cariAdiField;
        
        private string satisElemaniField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int baglantiLREF {
            get {
                return this.baglantiLREFField;
            }
            set {
                this.baglantiLREFField = value;
                this.RaisePropertyChanged("baglantiLREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int cariLREF {
            get {
                return this.cariLREFField;
            }
            set {
                this.cariLREFField = value;
                this.RaisePropertyChanged("cariLREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CariKodu {
            get {
                return this.cariKoduField;
            }
            set {
                this.cariKoduField = value;
                this.RaisePropertyChanged("CariKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CariAdi {
            get {
                return this.cariAdiField;
            }
            set {
                this.cariAdiField = value;
                this.RaisePropertyChanged("CariAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SatisElemani {
            get {
                return this.satisElemaniField;
            }
            set {
                this.satisElemaniField = value;
                this.RaisePropertyChanged("SatisElemani");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FiyatListesiBakiye : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fiyatListesiKoduField;
        
        private string aciklamaField;
        
        private string baglantiTutariField;
        
        private string siparisTutariField;
        
        private string bakiyeField;
        
        private string baglantiLREFField;
        
        private double iskontoOraniField;
        
        private double sozlesmeUSDField;
        
        private double sozlesmeEURField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fiyatListesiKodu {
            get {
                return this.fiyatListesiKoduField;
            }
            set {
                this.fiyatListesiKoduField = value;
                this.RaisePropertyChanged("fiyatListesiKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
                this.RaisePropertyChanged("Aciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string baglantiTutari {
            get {
                return this.baglantiTutariField;
            }
            set {
                this.baglantiTutariField = value;
                this.RaisePropertyChanged("baglantiTutari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string siparisTutari {
            get {
                return this.siparisTutariField;
            }
            set {
                this.siparisTutariField = value;
                this.RaisePropertyChanged("siparisTutari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string bakiye {
            get {
                return this.bakiyeField;
            }
            set {
                this.bakiyeField = value;
                this.RaisePropertyChanged("bakiye");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string baglantiLREF {
            get {
                return this.baglantiLREFField;
            }
            set {
                this.baglantiLREFField = value;
                this.RaisePropertyChanged("baglantiLREF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double iskontoOrani {
            get {
                return this.iskontoOraniField;
            }
            set {
                this.iskontoOraniField = value;
                this.RaisePropertyChanged("iskontoOrani");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double sozlesmeUSD {
            get {
                return this.sozlesmeUSDField;
            }
            set {
                this.sozlesmeUSDField = value;
                this.RaisePropertyChanged("sozlesmeUSD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double sozlesmeEUR {
            get {
                return this.sozlesmeEURField;
            }
            set {
                this.sozlesmeEURField = value;
                this.RaisePropertyChanged("sozlesmeEUR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SistemKalemleriBilgileri : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string koduField;
        
        private string adiField;
        
        private double birBirimeKullanilacakMiktarField;
        
        private double paketMiktariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Kodu {
            get {
                return this.koduField;
            }
            set {
                this.koduField = value;
                this.RaisePropertyChanged("Kodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
                this.RaisePropertyChanged("Adi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double BirBirimeKullanilacakMiktar {
            get {
                return this.birBirimeKullanilacakMiktarField;
            }
            set {
                this.birBirimeKullanilacakMiktarField = value;
                this.RaisePropertyChanged("BirBirimeKullanilacakMiktar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double paketMiktari {
            get {
                return this.paketMiktariField;
            }
            set {
                this.paketMiktariField = value;
                this.RaisePropertyChanged("paketMiktari");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZOKALEAPISoapChannel : KaleBlokBims.M2BWebService.IZOKALEAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZOKALEAPISoapClient : System.ServiceModel.ClientBase<KaleBlokBims.M2BWebService.IZOKALEAPISoap>, KaleBlokBims.M2BWebService.IZOKALEAPISoap {
        
        public ZOKALEAPISoapClient() {
        }
        
        public ZOKALEAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZOKALEAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZOKALEAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZOKALEAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable PaletFiyatiniAl() {
            return base.Channel.PaletFiyatiniAl();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PaletFiyatiniAlAsync() {
            return base.Channel.PaletFiyatiniAlAsync();
        }
        
        public KaleBlokBims.M2BWebService.Musteriler[] Bayiler() {
            return base.Channel.Bayiler();
        }
        
        public System.Threading.Tasks.Task<KaleBlokBims.M2BWebService.Musteriler[]> BayilerAsync() {
            return base.Channel.BayilerAsync();
        }
        
        public string IlveIlceleriGetir() {
            return base.Channel.IlveIlceleriGetir();
        }
        
        public System.Threading.Tasks.Task<string> IlveIlceleriGetirAsync() {
            return base.Channel.IlveIlceleriGetirAsync();
        }
        
        public KaleBlokBims.M2BWebService.SistemKalemleriBilgileri[] SistemKalemleriBilgileriAl(string anaGrup) {
            return base.Channel.SistemKalemleriBilgileriAl(anaGrup);
        }
        
        public System.Threading.Tasks.Task<KaleBlokBims.M2BWebService.SistemKalemleriBilgileri[]> SistemKalemleriBilgileriAlAsync(string anaGrup) {
            return base.Channel.SistemKalemleriBilgileriAlAsync(anaGrup);
        }
        
        public string MalzemeListesi(string BayiKodu, string FiyatListesiKodu, string baglantiLREF, string SPECODE1, string SPECODE2, string Il, string Ilce, bool fabrikaTeslimMi, double GuncelUSD, double GuncelEUR, string PAYPLANREF) {
            return base.Channel.MalzemeListesi(BayiKodu, FiyatListesiKodu, baglantiLREF, SPECODE1, SPECODE2, Il, Ilce, fabrikaTeslimMi, GuncelUSD, GuncelEUR, PAYPLANREF);
        }
        
        public System.Threading.Tasks.Task<string> MalzemeListesiAsync(string BayiKodu, string FiyatListesiKodu, string baglantiLREF, string SPECODE1, string SPECODE2, string Il, string Ilce, bool fabrikaTeslimMi, double GuncelUSD, double GuncelEUR, string PAYPLANREF) {
            return base.Channel.MalzemeListesiAsync(BayiKodu, FiyatListesiKodu, baglantiLREF, SPECODE1, SPECODE2, Il, Ilce, fabrikaTeslimMi, GuncelUSD, GuncelEUR, PAYPLANREF);
        }
        
        public string YonetimRaporlari(string tabloAdi) {
            return base.Channel.YonetimRaporlari(tabloAdi);
        }
        
        public System.Threading.Tasks.Task<string> YonetimRaporlariAsync(string tabloAdi) {
            return base.Channel.YonetimRaporlariAsync(tabloAdi);
        }
        
        public KaleBlokBims.M2BWebService.FiyatListesiBakiye[] SecilebilirFiyatListeleri(string BayiKodu) {
            return base.Channel.SecilebilirFiyatListeleri(BayiKodu);
        }
        
        public System.Threading.Tasks.Task<KaleBlokBims.M2BWebService.FiyatListesiBakiye[]> SecilebilirFiyatListeleriAsync(string BayiKodu) {
            return base.Channel.SecilebilirFiyatListeleriAsync(BayiKodu);
        }
        
        public string AnaGruplar(string FiyatListesi, string baglantiLREF, string BayiKodu) {
            return base.Channel.AnaGruplar(FiyatListesi, baglantiLREF, BayiKodu);
        }
        
        public System.Threading.Tasks.Task<string> AnaGruplarAsync(string FiyatListesi, string baglantiLREF, string BayiKodu) {
            return base.Channel.AnaGruplarAsync(FiyatListesi, baglantiLREF, BayiKodu);
        }
        
        public string HesapEkstresi(string BayiKodu) {
            return base.Channel.HesapEkstresi(BayiKodu);
        }
        
        public System.Threading.Tasks.Task<string> HesapEkstresiAsync(string BayiKodu) {
            return base.Channel.HesapEkstresiAsync(BayiKodu);
        }
        
        public string IrsaliyeFisiSatirlari(int stFicheRef) {
            return base.Channel.IrsaliyeFisiSatirlari(stFicheRef);
        }
        
        public System.Threading.Tasks.Task<string> IrsaliyeFisiSatirlariAsync(int stFicheRef) {
            return base.Channel.IrsaliyeFisiSatirlariAsync(stFicheRef);
        }
        
        public string MusteriyeSevkRaporu(string BayiKodu, string BaslangicTarih, string BitisTarihi) {
            return base.Channel.MusteriyeSevkRaporu(BayiKodu, BaslangicTarih, BitisTarihi);
        }
        
        public System.Threading.Tasks.Task<string> MusteriyeSevkRaporuAsync(string BayiKodu, string BaslangicTarih, string BitisTarihi) {
            return base.Channel.MusteriyeSevkRaporuAsync(BayiKodu, BaslangicTarih, BitisTarihi);
        }
        
        public string IrsaliyeFisleri(string BayiKodu) {
            return base.Channel.IrsaliyeFisleri(BayiKodu);
        }
        
        public System.Threading.Tasks.Task<string> IrsaliyeFisleriAsync(string BayiKodu) {
            return base.Channel.IrsaliyeFisleriAsync(BayiKodu);
        }
        
        public string SiparisFisiSatirIrsaliyeleri(int orfLineRef) {
            return base.Channel.SiparisFisiSatirIrsaliyeleri(orfLineRef);
        }
        
        public System.Threading.Tasks.Task<string> SiparisFisiSatirIrsaliyeleriAsync(int orfLineRef) {
            return base.Channel.SiparisFisiSatirIrsaliyeleriAsync(orfLineRef);
        }
        
        public string SiparisFisiSatirlari(int OrFicheRef) {
            return base.Channel.SiparisFisiSatirlari(OrFicheRef);
        }
        
        public System.Threading.Tasks.Task<string> SiparisFisiSatirlariAsync(int OrFicheRef) {
            return base.Channel.SiparisFisiSatirlariAsync(OrFicheRef);
        }
        
        public string SiparisFisleri(string BayiKodu) {
            return base.Channel.SiparisFisleri(BayiKodu);
        }
        
        public System.Threading.Tasks.Task<string> SiparisFisleriAsync(string BayiKodu) {
            return base.Channel.SiparisFisleriAsync(BayiKodu);
        }
        
        public string TumBayilerinBaglantiBakiyeOzeti() {
            return base.Channel.TumBayilerinBaglantiBakiyeOzeti();
        }
        
        public System.Threading.Tasks.Task<string> TumBayilerinBaglantiBakiyeOzetiAsync() {
            return base.Channel.TumBayilerinBaglantiBakiyeOzetiAsync();
        }
        
        public KaleBlokBims.M2BWebService.SozlesmeVeCarileri[] SozlesmeyeBagliCarilerVeSatisElemanlari() {
            return base.Channel.SozlesmeyeBagliCarilerVeSatisElemanlari();
        }
        
        public System.Threading.Tasks.Task<KaleBlokBims.M2BWebService.SozlesmeVeCarileri[]> SozlesmeyeBagliCarilerVeSatisElemanlariAsync() {
            return base.Channel.SozlesmeyeBagliCarilerVeSatisElemanlariAsync();
        }
        
        public string BaglantiBakiyeOzeti(string BayiKodu) {
            return base.Channel.BaglantiBakiyeOzeti(BayiKodu);
        }
        
        public System.Threading.Tasks.Task<string> BaglantiBakiyeOzetiAsync(string BayiKodu) {
            return base.Channel.BaglantiBakiyeOzetiAsync(BayiKodu);
        }
        
        public string HesapOzeti(string BayiKodu) {
            return base.Channel.HesapOzeti(BayiKodu);
        }
        
        public System.Threading.Tasks.Task<string> HesapOzetiAsync(string BayiKodu) {
            return base.Channel.HesapOzetiAsync(BayiKodu);
        }
        
        public string MusteriyeBagliCariBilgileri(string BayiKodu) {
            return base.Channel.MusteriyeBagliCariBilgileri(BayiKodu);
        }
        
        public System.Threading.Tasks.Task<string> MusteriyeBagliCariBilgileriAsync(string BayiKodu) {
            return base.Channel.MusteriyeBagliCariBilgileriAsync(BayiKodu);
        }
        
        public string WCFOdemePlanlari() {
            return base.Channel.WCFOdemePlanlari();
        }
        
        public System.Threading.Tasks.Task<string> WCFOdemePlanlariAsync() {
            return base.Channel.WCFOdemePlanlariAsync();
        }
        
        public string WCFSatisElemanlari() {
            return base.Channel.WCFSatisElemanlari();
        }
        
        public System.Threading.Tasks.Task<string> WCFSatisElemanlariAsync() {
            return base.Channel.WCFSatisElemanlariAsync();
        }
        
        public string IsyeriBilgileri() {
            return base.Channel.IsyeriBilgileri();
        }
        
        public System.Threading.Tasks.Task<string> IsyeriBilgileriAsync() {
            return base.Channel.IsyeriBilgileriAsync();
        }
        
        public string FabrikaBilgileri() {
            return base.Channel.FabrikaBilgileri();
        }
        
        public System.Threading.Tasks.Task<string> FabrikaBilgileriAsync() {
            return base.Channel.FabrikaBilgileriAsync();
        }
        
        public string BolumBilgileri() {
            return base.Channel.BolumBilgileri();
        }
        
        public System.Threading.Tasks.Task<string> BolumBilgileriAsync() {
            return base.Channel.BolumBilgileriAsync();
        }
        
        public string AmbarBilgileri() {
            return base.Channel.AmbarBilgileri();
        }
        
        public System.Threading.Tasks.Task<string> AmbarBilgileriAsync() {
            return base.Channel.AmbarBilgileriAsync();
        }
        
        public string WCFSozlesmeBilgileri(string BayiKodu, int BaglantiLREF) {
            return base.Channel.WCFSozlesmeBilgileri(BayiKodu, BaglantiLREF);
        }
        
        public System.Threading.Tasks.Task<string> WCFSozlesmeBilgileriAsync(string BayiKodu, int BaglantiLREF) {
            return base.Channel.WCFSozlesmeBilgileriAsync(BayiKodu, BaglantiLREF);
        }
        
        public string test() {
            return base.Channel.test();
        }
        
        public System.Threading.Tasks.Task<string> testAsync() {
            return base.Channel.testAsync();
        }
        
        public string M2BSiparisOlustur(string Ambar, KaleBlokBims.M2BWebService.M2BWCFBaslik Baslik, KaleBlokBims.M2BWebService.M2BWCFTransaction[] Transactions, KaleBlokBims.M2BWebService.CariSevkAdresi AdresBilgileri) {
            return base.Channel.M2BSiparisOlustur(Ambar, Baslik, Transactions, AdresBilgileri);
        }
        
        public System.Threading.Tasks.Task<string> M2BSiparisOlusturAsync(string Ambar, KaleBlokBims.M2BWebService.M2BWCFBaslik Baslik, KaleBlokBims.M2BWebService.M2BWCFTransaction[] Transactions, KaleBlokBims.M2BWebService.CariSevkAdresi AdresBilgileri) {
            return base.Channel.M2BSiparisOlusturAsync(Ambar, Baslik, Transactions, AdresBilgileri);
        }
    }
}
